### ISSUE TITLE
Data sets encoding. Sun 18

### ISSUE THREAD

**Issue by flovera1** [SANSA-Stack/Spark-RDF-Statistics#1]
Hi,
I am getting an error with this code:

org.openjena.riot.RiotParseException: [line: 1, col: 1 ] Bad character encoding

Bad character encoding, meaning that there is something wrong with the data. I downloaded the data set from dbpedia.org and the data set is ".nt". I removed the first headings of the file as they contain the spurious #. But still it doesn't work and gives the bad encoding error.
How do I fix this?.
Regards

**Comment by earthquakesan** [comment]
The README.md file should be fixed to include the whole working scenario. Including how to upload files to HDFS and how to run HDFS using docker containers.
@gezims can you please take a look into this?

**Comment by flovera1** [comment]
Hey!,
the data set I was working on is the following:
http://downloads.dbpedia.org/2015-10/links/amsterdammuseum_links.nt.bz2

I didn't do anything with it, just decompressed it and erase the first line!.

**Comment by GezimSejdiu** [comment]
Hi @flovera1,
thanks for you feedback.
This issue was injected cause of java -version, since jena on newest version do not support RiotReader. The project is switched to java8 and we are using RDFDataMgr instead of RiotReader.
Please, give it a try and let me know if you are facing the same error again.
B.t.w, there is no need to decompressed data and erase the first line (comment line), it is done automatically from spark decompressor and filter function.
We have provided Spark/HDFS Workbench in order to provide a runnable environment for Spark-RDF Statistics application.
